// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA51JMaSqm7gJtJ4hNMzSECMXHHycopy70',
    appId: '1:54156139550:web:a3040bb82defaaf61ce20f',
    messagingSenderId: '54156139550',
    projectId: 'sales-bets-c4f04',
    authDomain: 'sales-bets-c4f04.firebaseapp.com',
    storageBucket: 'sales-bets-c4f04.firebasestorage.app',
    measurementId: 'G-VWJ7PYRELE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3wiL-HXnnD5fBk0MESYLrk63wX9V11Ig',
    appId: '1:54156139550:android:90d6a6d1c26e15061ce20f',
    messagingSenderId: '54156139550',
    projectId: 'sales-bets-c4f04',
    storageBucket: 'sales-bets-c4f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmeEE3yz1PctGZ1JZT_CVbjD60kT63vA',
    appId: '1:54156139550:ios:bef6efc2809c0b1c1ce20f',
    messagingSenderId: '54156139550',
    projectId: 'sales-bets-c4f04',
    storageBucket: 'sales-bets-c4f04.firebasestorage.app',
    iosBundleId: 'com.example.salesBets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdmeEE3yz1PctGZ1JZT_CVbjD60kT63vA',
    appId: '1:54156139550:ios:bef6efc2809c0b1c1ce20f',
    messagingSenderId: '54156139550',
    projectId: 'sales-bets-c4f04',
    storageBucket: 'sales-bets-c4f04.firebasestorage.app',
    iosBundleId: 'com.example.salesBets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA51JMaSqm7gJtJ4hNMzSECMXHHycopy70',
    appId: '1:54156139550:web:0bfaedd1dddc91e81ce20f',
    messagingSenderId: '54156139550',
    projectId: 'sales-bets-c4f04',
    authDomain: 'sales-bets-c4f04.firebaseapp.com',
    storageBucket: 'sales-bets-c4f04.firebasestorage.app',
    measurementId: 'G-E737B5H6D4',
  );
}
